import { Schema, model, models, Types, type InferSchemaType } from "mongoose";

const SocialSchema = new Schema(
  {
    platform: { type: String, required: true }, // instagram, tiktok, youtube, ...
    url: { type: String, required: true },
  },
  { _id: false }
);

const TestimonialSchema = new Schema(
  {
    author: { type: String, required: true },
    role: { type: String, default: "" }, // e.g. "Marketing @ Brand"
    avatar: { type: String, default: null },
    quote: { type: String, required: true },
  },
  { _id: true }
);

const ClientSchema = new Schema(
  {
    name: { type: String, required: true },
    logo: { type: String, default: null },
    url: { type: String, default: null },
  },
  { _id: true }
);

const CaseSchema = new Schema(
  {
    title: { type: String, required: true },
    brand: { type: String, default: "" },
    description: { type: String, default: "" },
    result: { type: String, default: "" }, // e.g. "+180% de alcance"
    thumbnail: { type: String, default: null },
    link: { type: String, default: null },
  },
  { _id: true }
);

const SectionSchema = new Schema(
  {
    key: { type: String, required: true },
    enabled: { type: Boolean, default: true },
    order: { type: Number, default: 0 },
  },
  { _id: false }
);


const PortfolioSchema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    slug: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
      index: true,
    },
    templateSlug: { type: String, default: "aurora" },
    published: { type: Boolean, default: false },

    // Filled during onboarding
    profile: {
      fullName: { type: String, default: "" },
      username: { type: String, default: "" }, // public handle, mirrors slug
      photo: { type: String, default: null },
      city: { type: String, default: "" },
      country: { type: String, default: "" },
      languages: { type: [String], default: [] },
      ageRange: { type: String, default: "" }, // "18-24", "25-34"...
      pronouns: { type: String, default: "" },

      niches: { type: [String], default: [] }, // beauty, fitness, food, tech...
      experience: { type: String, default: "" }, // "iniciante" | "intermedia" | "experiente"
      contentTypes: { type: [String], default: [] },
      brandSegments: { type: [String], default: [] },
      communicationStyle: { type: String, default: "" },
      travelAvailability: { type: Boolean, default: false },
      productAvailability: { type: Boolean, default: false },

      bio: { type: String, default: "" }, // raw bio the user typed (optional)
      socials: { type: [SocialSchema], default: [] },
      equipment: { type: [String], default: [] }, // iPhone 15, Sony ZV-1...
    },

    // Generated by AI from the profile (editable by the user afterwards)
    ai: {
      headline: { type: String, default: "" },
      professionalBio: { type: String, default: "" },
      aboutMe: { type: String, default: "" },
      specialties: { type: [String], default: [] },
      brandDescription: { type: String, default: "" },
      ctaPrimary: { type: String, default: "" },
      ctaContact: { type: String, default: "" },
      generatedAt: { type: Date, default: null },
    },

    // Latest computed portfolio score (history lives in PortfolioScore)
    score: {
      total: { type: Number, default: 0 },
      updatedAt: { type: Date, default: null },
    },

    // Visual overrides on top of the chosen template
    theme: {
      accent: { type: String, default: null }, // hex/oklch override
      font: { type: String, default: null }, // "sans" | "serif"
    },

    // Section visibility/order for the editor. Empty = template default order.
    sections: { type: [SectionSchema], default: [] },

    categories: { type: [String], default: [] },
    testimonials: { type: [TestimonialSchema], default: [] },
    clients: { type: [ClientSchema], default: [] },
    cases: { type: [CaseSchema], default: [] },
  },
  { timestamps: true }
);

export type PortfolioDoc = InferSchemaType<typeof PortfolioSchema> & {
  _id: Types.ObjectId;
};

export const Portfolio =
  models.Portfolio || model("Portfolio", PortfolioSchema);
